version: 2.1

orbs:
  gradle-publish: freeletics/gradle-publish@1.1.1

# Common anchors
# PR cache anchors
gradle_cache_key: &gradle_cache_key
  key: v1-dependencies-{{ checksum "dependencies.gradle" }}
restore_gradle_cache: &restore_gradle_cache
  restore_cache:
    <<: *gradle_cache_key
save_gradle_cache: &save_gradle_cache
  save_cache:
    <<: *gradle_cache_key
    paths:
      - ~/.gradle/caches
      - ~/.gradle/wrapper

executors:
  android:
    docker:
      - image: circleci/android:api-28
    working_directory: ~/repo
    environment:
      JAVA_TOOL_OPTIONS: "-Xmx1536m"
      GRADLE_OPTS: "-Dorg.gradle.daemon=false -Dorg.gradle.workers.max=2 -Dkotlin.incremental=false"
      TERM: dumb

  macos:
    parameters:
      resource_class:
        type: string
        default: medium
    macos:
      xcode: 11.7.0
  mkdocs:
    docker:
      - image: circleci/python:3.7.6
    working_directory: ~/repo

jobs:
  build_and_test:
    executor: macos
    steps:
      - checkout
      - *restore_gradle_cache
      - run:
          name: Build and test library and dsl
          command: ./gradlew :flowredux:build :dsl:build --stacktrace
      - *save_gradle_cache
  deploy_website:
    executor: mkdocs
    steps:
      - run:
          name: Setup mkdocs and material theme
          command: |
            pip install mkdocs
            pip install mkdocs-material
      - run:
          name: Set Git config
          command: |
            git config --global user.email "$GIT_AUTHOR_EMAIL"
            git config --global user.name "$GIT_AUTHOR_NAME"
            git config --global user.signingkey "$GIT_SIGNING_KEY"
            git config --global commit.gpgsign true
            export PRIVATE_KEY_FILE=`mktemp`
            echo $GPG_PRIVATE_KEY | base64 -d > $PRIVATE_KEY_FILE
            gpg --import $PRIVATE_KEY_FILE
      - checkout
      - run:
          name: Deploy Website
          command: ./deploy_website.sh

workflows:
  version: 2

  master-pipeline:
    jobs:
      - build_and_test:
          filters:
            branches:
              only:
                - master
      - deploy_website:
          context: "Commit Signing"
          requires:
            - gradle-publish/publish_artifacts
          filters:
            branches:
              only:
                - master
      - gradle-publish/publish_artifacts:
          executor: gradle-publish/circleci-macos
          context: "android-maven-publish"
          deploy_task: "publish"
          requires:
            - build_and_test

  check-pr:
    jobs:
      - build_and_test:
          filters:
            branches:
              ignore:
                - master
                - gh-pages
